"""CoAPT Mid-training adapters; planned Post-training uses separate trainer contracts."""
from typing import Callable, Protocol


class Teacher(Protocol):
    def curriculum(self, brief: dict) -> dict: ...
    def revise(self, lessons: list[dict]) -> list[dict]: ...
    def select_materials(self, manifest: dict) -> dict: ...
    def evaluate(self, curriculum: dict, lessons: list[dict]) -> list[dict]: ...
    def grade(self, items: list[dict]) -> list[dict]: ...
    def reflect(self, observations: dict) -> dict: ...


class Student(Protocol):
    def generate(self, checkpoint: str, rows: list[dict], on_answer: Callable) -> list[dict]: ...
    def compare(self, checkpoint: str, reference: str, rows: list[dict], on_answer: Callable, *, reference_format: str | None = None) -> dict: ...


class Trainer(Protocol):
    def prepare(self, checkpoint: str, rows: list[dict]) -> dict: ...
    def train(self, checkpoint: str, dataset: dict, dataset_hash: str, on_metric: Callable) -> dict: ...
